#!/bin/sh
#
# Plugin to monitor the number of principals stored in the cassandra CF.

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

HOME=/tmp/
cd $HOME

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then
        echo 'graph_title Cassandra principals'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel cassandra principals'
        echo 'graph_category OAE'
        echo 'principals.label principals'
        exit 0
fi

# Get the data from Cassandra
echo 'SELECT count(*) from Principals;' > /tmp/users.cql
echo `cqlsh -f /tmp/users.cql -k oae | grep "[0-9]" | awk {'print $1'}`